#!/usr/bin/env python3
"""
Interactive setup wizard for pdf-to-obsidian.

Creates a virtual environment, installs dependencies, and writes a .env file
with the user's API keys and Obsidian vault path.
"""

from __future__ import annotations

import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

MIN_PYTHON = (3, 10)
PROJECT_ROOT = Path(__file__).resolve().parent
VENV_DIR = PROJECT_ROOT / "venv"
ENV_FILE = PROJECT_ROOT / ".env"
ENV_EXAMPLE = PROJECT_ROOT / ".env.example"


def header(title: str) -> None:
    print()
    print("=" * 50)
    print(f"  {title}")
    print("=" * 50)
    print()


def check_python_version() -> None:
    if sys.version_info < MIN_PYTHON:
        version = ".".join(str(part) for part in sys.version_info[:3])
        required = ".".join(str(part) for part in MIN_PYTHON)
        print(f"[ERROR] Python {required}+ is required. You are running {version}.")
        print("        Install a newer Python from https://www.python.org/downloads/")
        sys.exit(1)


def prompt(text: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{text}{suffix}: ").strip()
    return value or default


def prompt_secret(text: str) -> str:
    try:
        import getpass

        return getpass.getpass(f"{text}: ").strip()
    except Exception:
        return input(f"{text}: ").strip()


def choose_vault_path() -> str:
    print()
    print("Obsidian vault path")
    print("  This should be the folder that contains your Obsidian notes.")
    print("  Example (Windows): C:\\Users\\You\\Documents\\My Vault")
    print("  Example (Mac):     /Users/you/Documents/My Vault")
    print()

    while True:
        print("How would you like to choose your vault folder?")
        print("  1) Type the path manually")
        print("  2) Open a folder picker")
        choice = prompt("Choose 1 or 2", "1")

        if choice == "2":
            path = pick_folder_dialog()
            if path:
                return validate_vault_path(path)
            print("[INFO] Folder picker cancelled. Try again.")
            continue

        path = prompt("Enter the full path to your Obsidian vault")
        return validate_vault_path(path)


def pick_folder_dialog() -> str | None:
    try:
        import tkinter as tk
        from tkinter import filedialog

        root = tk.Tk()
        root.withdraw()
        root.attributes("-topmost", True)
        selected = filedialog.askdirectory(title="Select your Obsidian vault folder")
        root.destroy()
        return selected or None
    except Exception as exc:
        print(f"[WARN] Could not open folder picker: {exc}")
        return None


def validate_vault_path(path: str) -> str:
    cleaned = os.path.expanduser(path.strip().strip('"').strip("'"))
    cleaned = os.path.abspath(cleaned)

    if not cleaned:
        print("[ERROR] Vault path cannot be empty.")
        return choose_vault_path()

    if not os.path.isdir(cleaned):
        create = prompt(
            f"Folder not found:\n  {cleaned}\nCreate it now? (y/n)",
            "y",
        ).lower()
        if create in {"y", "yes"}:
            os.makedirs(cleaned, exist_ok=True)
            print(f"[OK] Created folder: {cleaned}")
            return cleaned
        print("[INFO] Let's try again.")
        return choose_vault_path()

    print(f"[OK] Vault path: {cleaned}")
    return cleaned


def create_venv() -> Path:
    if VENV_DIR.exists():
        print(f"[OK] Virtual environment already exists at {VENV_DIR}")
        return python_in_venv()

    print("Creating virtual environment...")
    subprocess.run([sys.executable, "-m", "venv", str(VENV_DIR)], check=True)
    print("[OK] Virtual environment created.")
    return python_in_venv()


def python_in_venv() -> Path:
    if platform.system() == "Windows":
        return VENV_DIR / "Scripts" / "python.exe"
    return VENV_DIR / "bin" / "python"


def install_dependencies(venv_python: Path) -> None:
    requirements = PROJECT_ROOT / "requirements.txt"
    print("Installing Python dependencies...")
    subprocess.run(
        [str(venv_python), "-m", "pip", "install", "--upgrade", "pip"],
        check=True,
    )
    subprocess.run(
        [str(venv_python), "-m", "pip", "install", "-r", str(requirements)],
        check=True,
    )
    print("[OK] Dependencies installed.")


def write_env_file(gemini_key: str, vault_path: str) -> None:
    lines = [
        "# Generated by setup.py",
        f"GEMINI_API_KEY={gemini_key}",
        f"OBSIDIAN_VAULT_PATH={vault_path}",
        "",
        "# Optional settings",
        "# GEMINI_MODEL=gemini-3.5-flash",
        "# PDF_DPI=300",
        "# MAX_RETRIES=5",
        "",
    ]

    ENV_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"[OK] Wrote configuration to {ENV_FILE}")


def maybe_copy_example_env() -> None:
    if ENV_FILE.exists():
        overwrite = prompt(".env already exists. Overwrite it? (y/n)", "n").lower()
        if overwrite not in {"y", "yes"}:
            print("[INFO] Keeping your existing .env file.")
            sys.exit(0)


def print_next_steps() -> None:
    system = platform.system()
    header("Setup complete")

    print("You're ready to run pdf-to-obsidian.")
    print()
    print("Next steps:")
    if system == "Windows":
        print("  1. Double-click run.bat")
        print("  2. Or run: venv\\Scripts\\activate && python app.py")
    else:
        print("  1. Run: chmod +x run.sh && ./run.sh")
        print("  2. Or run: source venv/bin/activate && python app.py")
    print("  3. Open http://localhost:5000 in your browser")
    print()
    print("Bring your own Gemini API key. Get one free at:")
    print("  https://aistudio.google.com/apikey")
    print()


def main() -> None:
    os.chdir(PROJECT_ROOT)
    header("pdf-to-obsidian setup")

    check_python_version()
    maybe_copy_example_env()

    print("This wizard will:")
    print("  - create a Python virtual environment")
    print("  - install dependencies")
    print("  - save your Gemini API key and Obsidian vault path to .env")
    print()

    gemini_key = prompt_secret("Gemini API key")
    while not gemini_key:
        print("[ERROR] Gemini API key is required.")
        gemini_key = prompt_secret("Gemini API key")

    vault_path = choose_vault_path()

    venv_python = create_venv()
    install_dependencies(venv_python)
    write_env_file(gemini_key, vault_path)
    print_next_steps()


if __name__ == "__main__":
    try:
        main()
    except subprocess.CalledProcessError as exc:
        print(f"[ERROR] Setup command failed with exit code {exc.returncode}.")
        sys.exit(exc.returncode)
    except KeyboardInterrupt:
        print("\n[INFO] Setup cancelled.")
        sys.exit(1)
